<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Product>ErpHub</Product>
    <Authors>Blagojević Boban</Authors>
    <Company>Blagojević Boban</Company>

    <!-- Čitamo verziju direktno iz version.txt -->
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)\version.txt').Trim())</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>

