<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Product>ERPiHub</Product>
    <Authors>Blagojević Boban</Authors>
    <Company>Blagojević Boban</Company>
    <ApplicationIcon>app.ico</ApplicationIcon>

    <!-- Čitamo verziju direktno iz version.txt -->
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)\version.txt').Trim())</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
